package com.openwallet.ledger.domain;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Diagnostic test to inspect the database schema and verify LedgerEntry ID generation.
 * This test helps identify issues with table creation and ID auto-generation.
 */
@DataJpaTest
@Import(com.openwallet.ledger.config.JpaConfig.class)
@ActiveProfiles("test")
@DisplayName("LedgerEntry Schema and ID Generation Diagnostic")
class LedgerEntrySchemaTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PersistenceContext
    private EntityManager entityManager;

    @Test
    @DisplayName("Should verify ledger_entries table exists")
    void shouldVerifyTableExists() {
        // Check if table exists
        String sql = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES " +
                     "WHERE TABLE_NAME = 'ledger_entries'";
        
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class);
        assertThat(count).isEqualTo(1);
        
        System.out.println("✓ Table 'ledger_entries' exists");
    }

    @Test
    @DisplayName("Should inspect ledger_entries table structure")
    void shouldInspectTableStructure() {
        // Get column information
        String sql = "SELECT " +
                     "    column_name, " +
                     "    data_type, " +
                     "    is_nullable, " +
                     "    column_default, " +
                     "    character_maximum_length " +
                     "FROM INFORMATION_SCHEMA.COLUMNS " +
                     "WHERE TABLE_NAME = 'ledger_entries' " +
                     "ORDER BY ordinal_position";
        
        List<Map<String, Object>> columns = jdbcTemplate.queryForList(sql);
        
        System.out.println("\n=== ledger_entries Table Structure ===");
        for (Map<String, Object> column : columns) {
            System.out.printf("Column: %-20s | Type: %-20s | Nullable: %-5s | Default: %s%n",
                    column.get("column_name"),
                    column.get("data_type"),
                    column.get("is_nullable"),
                    column.get("column_default"));
        }
        
        // Verify ID column specifically
        Map<String, Object> idColumn = columns.stream()
                .filter(c -> "id".equals(c.get("column_name")))
                .findFirst()
                .orElseThrow(() -> new AssertionError("ID column not found"));
        
        System.out.println("\n=== ID Column Details ===");
        System.out.println("Data Type: " + idColumn.get("data_type"));
        System.out.println("Nullable: " + idColumn.get("is_nullable"));
        System.out.println("Default: " + idColumn.get("column_default"));
        
        // Check if it's an auto-increment column
        String dataType = (String) idColumn.get("data_type");
        String columnDefault = idColumn.get("column_default") != null 
                ? idColumn.get("column_default").toString() 
                : "null";
        
        assertThat(dataType).isIn("BIGINT", "INTEGER", "BIGSERIAL");
        System.out.println("\n✓ ID column exists with appropriate type");
    }

    @Test
    @DisplayName("Should verify ID column is auto-increment")
    void shouldVerifyIdAutoIncrement() {
        // Check for sequence or auto-increment
        String checkSequence = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SEQUENCES " +
                               "WHERE SEQUENCE_NAME LIKE '%ledger_entries%' OR " +
                               "      SEQUENCE_NAME LIKE '%id%'";
        
        // For H2, check if ID has AUTO_INCREMENT or GENERATED BY DEFAULT AS IDENTITY
        String checkAutoIncrement = "SELECT COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS " +
                                    "WHERE TABLE_NAME = 'ledger_entries' AND COLUMN_NAME = 'id'";
        
        String defaultValue = jdbcTemplate.queryForObject(checkAutoIncrement, String.class);
        
        System.out.println("\n=== ID Auto-Increment Check ===");
        System.out.println("ID Column Default Value: " + defaultValue);
        
        // H2 uses "NEXT VALUE FOR" or "AUTO_INCREMENT" or "GENERATED BY DEFAULT AS IDENTITY"
        assertThat(defaultValue)
                .as("ID column should have auto-increment default")
                .isNotNull();
        
        System.out.println("✓ ID column has auto-increment configured");
    }

    @Test
    @DisplayName("Should test direct LedgerEntry persistence")
    void shouldTestDirectLedgerEntryPersistence() {
        // First, create a Transaction (required foreign key)
        Transaction transaction = Transaction.builder()
                .transactionType(TransactionType.DEPOSIT)
                .amount(new BigDecimal("100.00"))
                .currency("KES")
                .toWalletId(1L)
                .status(TransactionStatus.PENDING)
                .idempotencyKey("test-tx-1")
                .build();
        
        entityManager.persist(transaction);
        entityManager.flush();
        
        System.out.println("\n=== Testing LedgerEntry Persistence ===");
        System.out.println("Created Transaction with ID: " + transaction.getId());
        
        // Now try to create a LedgerEntry using the builder
        LedgerEntry entry = LedgerEntry.builder()
                .transaction(transaction)
                .walletId(1L)
                .accountType("WALLET_1")
                .entryType(EntryType.CREDIT)
                .amount(new BigDecimal("100.00"))
                .balanceAfter(new BigDecimal("100.00"))
                .build();
        
        System.out.println("Created LedgerEntry with ID (before persist): " + entry.getId());
        System.out.println("LedgerEntry transaction: " + entry.getTransaction());
        System.out.println("LedgerEntry amount: " + entry.getAmount());
        
        // Persist and flush
        entityManager.persist(entry);
        entityManager.flush();
        
        System.out.println("LedgerEntry ID (after persist): " + entry.getId());
        System.out.println("LedgerEntry createdAt: " + entry.getCreatedAt());
        
        assertThat(entry.getId())
                .as("ID should be auto-generated after persist")
                .isNotNull();
        
        assertThat(entry.getCreatedAt())
                .as("createdAt should be auto-populated")
                .isNotNull();
        
        System.out.println("✓ LedgerEntry persisted successfully with auto-generated ID");
    }

    @Test
    @DisplayName("Should verify table has correct constraints")
    void shouldVerifyTableConstraints() {
        // Check for primary key
        String pkSql = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS " +
                       "WHERE TABLE_NAME = 'ledger_entries' " +
                       "AND CONSTRAINT_TYPE = 'PRIMARY KEY'";
        
        Integer pkCount = jdbcTemplate.queryForObject(pkSql, Integer.class);
        assertThat(pkCount).isEqualTo(1);
        
        System.out.println("✓ Primary key constraint exists");
        
        // Check for foreign key
        String fkSql = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS " +
                       "WHERE TABLE_NAME = 'ledger_entries' " +
                       "AND CONSTRAINT_TYPE = 'FOREIGN KEY'";
        
        Integer fkCount = jdbcTemplate.queryForObject(fkSql, Integer.class);
        System.out.println("Foreign key constraints: " + fkCount);
        
        // List all constraints
        String allConstraintsSql = "SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE " +
                                   "FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS " +
                                   "WHERE TABLE_NAME = 'ledger_entries'";
        
        List<Map<String, Object>> constraints = jdbcTemplate.queryForList(allConstraintsSql);
        System.out.println("\n=== Table Constraints ===");
        for (Map<String, Object> constraint : constraints) {
            System.out.println("Constraint: " + constraint.get("CONSTRAINT_NAME") + 
                             " | Type: " + constraint.get("CONSTRAINT_TYPE"));
        }
    }

    @Test
    @DisplayName("Should test direct SQL insert to verify ID generation")
    void shouldTestDirectSqlInsert() {
        // First, create a Transaction
        Transaction transaction = Transaction.builder()
                .transactionType(TransactionType.DEPOSIT)
                .amount(new BigDecimal("100.00"))
                .currency("KES")
                .toWalletId(1L)
                .status(TransactionStatus.PENDING)
                .idempotencyKey("test-tx-sql-1")
                .build();
        
        entityManager.persist(transaction);
        entityManager.flush();
        
        Long txId = transaction.getId();
        System.out.println("\n=== Testing Direct SQL Insert ===");
        System.out.println("Transaction ID: " + txId);
        
        // Try to insert directly via SQL without specifying ID
        String insertSql = "INSERT INTO ledger_entries " +
                          "(transaction_id, wallet_id, account_type, entry_type, amount, balance_after, created_at) " +
                          "VALUES (?, ?, ?, ?, ?, ?, ?)";
        
        try {
            int rowsAffected = jdbcTemplate.update(insertSql,
                    txId,
                    1L,
                    "WALLET_1",
                    "CREDIT",
                    new BigDecimal("100.00"),
                    new BigDecimal("100.00"),
                    java.time.LocalDateTime.now()
            );
            
            System.out.println("Rows affected: " + rowsAffected);
            
            // Query back to see if ID was generated
            String selectSql = "SELECT id, transaction_id, amount FROM ledger_entries WHERE transaction_id = ?";
            Map<String, Object> result = jdbcTemplate.queryForMap(selectSql, txId);
            
            System.out.println("Inserted row - ID: " + result.get("id"));
            System.out.println("Inserted row - Transaction ID: " + result.get("transaction_id"));
            System.out.println("Inserted row - Amount: " + result.get("amount"));
            
            assertThat(result.get("id"))
                    .as("ID should be auto-generated by database")
                    .isNotNull();
            
            System.out.println("✓ Direct SQL insert works - ID is auto-generated");
            
        } catch (Exception e) {
            System.err.println("ERROR during direct SQL insert:");
            e.printStackTrace();
            throw e;
        }
    }

    @Test
    @DisplayName("Should compare Hibernate vs SQL insert behavior")
    void shouldCompareHibernateVsSqlInsert() {
        // Create transaction
        Transaction transaction = Transaction.builder()
                .transactionType(TransactionType.DEPOSIT)
                .amount(new BigDecimal("200.00"))
                .currency("KES")
                .toWalletId(2L)
                .status(TransactionStatus.PENDING)
                .idempotencyKey("test-tx-compare-1")
                .build();
        
        entityManager.persist(transaction);
        entityManager.flush();
        
        System.out.println("\n=== Comparing Hibernate vs SQL Insert ===");
        
        // Method 1: Hibernate/JPA
        LedgerEntry hibernateEntry = LedgerEntry.builder()
                .transaction(transaction)
                .walletId(2L)
                .accountType("WALLET_2")
                .entryType(EntryType.CREDIT)
                .amount(new BigDecimal("200.00"))
                .balanceAfter(new BigDecimal("200.00"))
                .build();
        
        System.out.println("Hibernate Entry - ID before persist: " + hibernateEntry.getId());
        System.out.println("Hibernate Entry - Transaction: " + hibernateEntry.getTransaction().getId());
        
        try {
            entityManager.persist(hibernateEntry);
            entityManager.flush();
            
            System.out.println("Hibernate Entry - ID after persist: " + hibernateEntry.getId());
            System.out.println("Hibernate Entry - createdAt: " + hibernateEntry.getCreatedAt());
            System.out.println("✓ Hibernate persist succeeded");
            
            assertThat(hibernateEntry.getId()).isNotNull();
            
        } catch (Exception e) {
            System.err.println("✗ Hibernate persist FAILED:");
            e.printStackTrace();
            throw e;
        }
    }
}

